#!/system/bin/sh
#
# its me zyarexx
# SPDX-License-Identifier: GPL-3.0-or-later
#
abuHitam='\e[01;90m' 2>/dev/null 1>/dev/null # abu abu - hitam
putihHitam='\e[01;40m' 2>/dev/null 1>/dev/null # putih - hitam
merahHitam='\e[01;91m' 2>/dev/null 1>/dev/null # merah - hitam
merahPutih='\e[01;41m' 2>/dev/null 1>/dev/null # merah - putih
kuningHitam='\e[01;93m' 2>/dev/null 1>/dev/null # kuning - hitam
kuningPutih='\e[01;43m' 2>/dev/null 1>/dev/null # kuning - putih
biruHitam='\e[01;94m' 2>/dev/null 1>/dev/null # biru - hitam
biruPutih='\e[01;104m' 2>/dev/null 1>/dev/null # biru - putih
cyanHitam='\e[01;96m' 2>/dev/null 1>/dev/null # cyan - hitam
cyanPutih='\e[01;46m' 2>/dev/null 1>/dev/null # cyan - putih
hijauHitam='\e[01;92m' 2>/dev/null 1>/dev/null # hijau - hitam
hijauPutih='\e[01;42m' 2>/dev/null 1>/dev/null # hijau - putih
unguHitam='\e[01;95m' 2>/dev/null 1>/dev/null # ungu - hitam
unguPutih='\e[01;45m' 2>/dev/null 1>/dev/null # ungu - putih
ResetWarna='\e[0m' 2>/dev/null 1>/dev/null # Buat Reser Warna
if [ "$(id -u)" -gt "0" ] && [ "$(whoami)" != "root" ]; then
    echo $merahHitam"please type 'su' first -_-"$ResetWarna
    echo ""
    echo "Exit after :"
    for timeExit in 3s 2s 1s 0s
    do
        echo "$timeExit"
        sleep 1s
    done
    exit -1
fi
clear
. /system/etc/XCore/misc/get-bb.sh
echo "cmds: x_fsync ${@}"
disableFsync(){
        WriteFsync "0" "N" && echo "Disabled fsync Success"
}

enableFsync(){
        WriteFsync "1" "Y" && echo "Enable fsync Success"
}

CheckFsync(){
    if [[ -f /sys/kernel/dyn_fsync/Dyn_fsync_active ]] || [[ -f /sys/class/misc/fsynccontrol/fsync_enabled ]] || [[ -f /sys/module/sync/parameters/fsync ]] || [[ -f /sys/module/sync/parameters/fsync_enabled ]];then
        echo "y"
    else
        echo "n"
    fi
}

CheckFsyncMode(){
    if [[ "$(CheckFsync)" == "y" ]];then
        local show="n"
        local TypeFsync=""
        for getFsync in /sys/kernel/dyn_fsync/Dyn_fsync_active sys/class/misc/fsynccontrol/fsync_enabled /sys/module/sync/parameters/fsync /sys/module/sync/parameters/fsync_enabled
        do
            if [[ "$show" == "n" ]] && [[ -f "$getFsync" ]];then
                TypeFsync="$(cat $getFsync)"
                show="y"
            fi
        done
        if [[ "$show" == "y" ]];then
            if [[ "$TypeFsync" == "0" ]] || [[ "$TypeFsync" == "N" ]];then
                echo "Enabled"
            elif [[ "$TypeFsync" == "1" ]] || [[ "$TypeFsync" == "Y" ]];then
                echo "Disabled"
            fi
        fi
    fi
}

WriteFsync(){
    WriteOnly "$1" /sys/kernel/dyn_fsync/Dyn_fsync_active
    WriteOnly "$1" /sys/class/misc/fsynccontrol/fsync_enabled
    WriteOnly "$1" /sys/module/sync/parameters/fsync
    WriteOnly "$2" /sys/module/sync/parameters/fsync_enabled
}

WriteOnly(){
    [[ -f ${2} ]] && echo "${1}" > "${2}"
}

GetInfo(){
    echo "Fsync Status: $(CheckFsyncMode)"
}
if [[ "$(CheckFsync)" == "y" ]];then
    if [[ ! -z "${1}" ]];then
        if [[ "${1}" == "0" ]];then
            disableFsync
        elif [[ "${1}" == "1" ]];then
            enableFsync
        else
            GetInfo
        fi
    else
        GetInfo
    fi
else
    echo "ur kernel not supported this tweak"
fi