#!/system/bin/sh
#
# its me zyarexx
# SPDX-License-Identifier: GPL-3.0-or-later
#
abuHitam='\e[01;90m' 2>/dev/null 1>/dev/null # abu abu - hitam
putihHitam='\e[01;40m' 2>/dev/null 1>/dev/null # putih - hitam
merahHitam='\e[01;91m' 2>/dev/null 1>/dev/null # merah - hitam
merahPutih='\e[01;41m' 2>/dev/null 1>/dev/null # merah - putih
kuningHitam='\e[01;93m' 2>/dev/null 1>/dev/null # kuning - hitam
kuningPutih='\e[01;43m' 2>/dev/null 1>/dev/null # kuning - putih
biruHitam='\e[01;94m' 2>/dev/null 1>/dev/null # biru - hitam
biruPutih='\e[01;104m' 2>/dev/null 1>/dev/null # biru - putih
cyanHitam='\e[01;96m' 2>/dev/null 1>/dev/null # cyan - hitam
cyanPutih='\e[01;46m' 2>/dev/null 1>/dev/null # cyan - putih
hijauHitam='\e[01;92m' 2>/dev/null 1>/dev/null # hijau - hitam
hijauPutih='\e[01;42m' 2>/dev/null 1>/dev/null # hijau - putih
unguHitam='\e[01;95m' 2>/dev/null 1>/dev/null # ungu - hitam
unguPutih='\e[01;45m' 2>/dev/null 1>/dev/null # ungu - putih
ResetWarna='\e[0m' 2>/dev/null 1>/dev/null # Buat Reser Warna
if [ "$(id -u)" -gt "0" ] && [ "$(whoami)" != "root" ]; then
    echo $merahHitam"please type 'su' first -_-"$ResetWarna
    echo ""
    echo "Exit after :"
    for timeExit in 3s 2s 1s 0s
    do
        echo "$timeExit"
        sleep 1s
    done
    exit -1
fi
clear
. /system/etc/XCore/misc/get-bb.sh
. /system/etc/XCore/misc/initialize.sh
GameList=$MPATH/system/etc/XCore/configs/game_list.conf
echo "cmds: x_g ${@}"

RegenGameList(){
    echo "---->> List-game-installed-start <<----" > $GameList
    echo "<<---- List-game-installed-end ---->>" >> $GameList
    detectedAsGame=""
    for ListGame in $(cat $MPATH/system/etc/XCore/configs/manual_game_list.conf)
    do
        for GetGameId in $(pm list packages -3 | grep "${ListGame}" | awk -F= '{sub("package:","");print $1}')
        do
            if [[ ! -z $(pm list packages -f "$GetGameId" | awk -F '\\.apk' '{print $1".apk"}' | sed 's/package:*//g') ]] && [[ -z $( grep "$GetGameId" "$GameList" ) ]]; then
                sed -i "1a  $GetGameId" $GameList
                detectedAsGame="$GetGameId $detectedAsGame"
            fi
        done
    done
    echo "List Detected Games: $detectedAsGame"
}

ShowGameList(){
    cat $GameList
}

Gethelp(){
    echo "Quick info: "
    echo "h or help or anything: to show this"
    echo "r or regen : to re-generate game list"
    echo "s or show : to show generated game list"
    echo "u or update : to update manual game list"
    echo "example : x_g help"
}

AddManual(){
    if [[ -z "${1}" ]];then
        echo "no package id defined, example : x_g ${CallFunc} com.mobile.legends"
    else
        
        if [[ "$(cat $MPATH/system/etc/XCore/configs/manual_game_list.conf)" == *"${1}"* ]];then
            UpdateManual="n"
        else
            UpdateManual="y"
        fi
        if [[ "$(cat $GameList)" == *"${1}"* ]];then
            UpdateGameList="n"
        else
            UpdateGameList="y"
        fi
        [[ "${UpdateManual}" == "y" ]] && sed -i "1a  ${1}" $MPATH/system/etc/XCore/configs/manual_game_list.conf
        [[ "${UpdateGameList}" == "y" ]] && RegenGameList
        echo "Add Manual Done"
    fi
}

if [[ ! -z "${1}" ]];then
    if [[ "${1}" == "regen" ]] || [[ "${1}" == "r" ]];then
        RegenGameList
    elif [[ "${1}" == "show" ]] || [[ "${1}" == "s" ]];then
        ShowGameList
    elif [[ "${1}" == "update" ]] || [[ "${1}" == "u" ]];then
        CallFunc=${1}
        AddManual "${2}"
    elif [[ "${1}" == "help" ]] || [[ "${1}" == "h" ]];then
        Gethelp
    fi
else
    Gethelp
fi
