#!/system/bin/sh
#
# its me zyarexx
# SPDX-License-Identifier: GPL-3.0-or-later
#
abuHitam='\e[01;90m' 2>/dev/null 1>/dev/null # abu abu - hitam
putihHitam='\e[01;40m' 2>/dev/null 1>/dev/null # putih - hitam
merahHitam='\e[01;91m' 2>/dev/null 1>/dev/null # merah - hitam
merahPutih='\e[01;41m' 2>/dev/null 1>/dev/null # merah - putih
kuningHitam='\e[01;93m' 2>/dev/null 1>/dev/null # kuning - hitam
kuningPutih='\e[01;43m' 2>/dev/null 1>/dev/null # kuning - putih
biruHitam='\e[01;94m' 2>/dev/null 1>/dev/null # biru - hitam
biruPutih='\e[01;104m' 2>/dev/null 1>/dev/null # biru - putih
cyanHitam='\e[01;96m' 2>/dev/null 1>/dev/null # cyan - hitam
cyanPutih='\e[01;46m' 2>/dev/null 1>/dev/null # cyan - putih
hijauHitam='\e[01;92m' 2>/dev/null 1>/dev/null # hijau - hitam
hijauPutih='\e[01;42m' 2>/dev/null 1>/dev/null # hijau - putih
unguHitam='\e[01;95m' 2>/dev/null 1>/dev/null # ungu - hitam
unguPutih='\e[01;45m' 2>/dev/null 1>/dev/null # ungu - putih
ResetWarna='\e[0m' 2>/dev/null 1>/dev/null # Buat Reser Warna
if [ "$(id -u)" -gt "0" ] && [ "$(whoami)" != "root" ]; then
    echo $merahHitam"please type 'su' first -_-"$ResetWarna
    echo ""
    echo "Exit after :"
    for timeExit in 3s 2s 1s 0s
    do
        echo "$timeExit"
        sleep 1s
    done
    exit -1
fi
clear
. /system/etc/XCore/misc/get-bb.sh
. /system/etc/XCore/misc/initialize.sh
ModulesMode="$MPATH/system/etc/XCore/configs/modules_mode.conf"
echo "cmds: x_m ${@}"

Gethelp(){
    echo "Quick info: "
    echo "help : to show this"
    echo "off : force turn off modules"
    echo "on : force turn on modules"
    echo "app : modules mode depend detected app"
    echo "gpu : modules mode depend detected app"
    echo "display : modules mode depend display status"
    echo "auto : modules mode depend detected app and gpu usage"
    echo "anything or info : modules mode status"
    echo "example : x_m auto"
}
forceON(){
    echo "Force On" > $ModulesMode
    echo "update mode to 'Force On' done"
}
forceOFF(){
    echo "Force Off" > $ModulesMode
    echo "update mode to 'Force OFF' done"

}
SetToByApp(){
    echo "Depend App" > $ModulesMode
    echo "update mode to 'Depend App' done"

}
SetToByGpu(){
    echo "Depend GPU Usage" > $ModulesMode
    echo "update mode to 'Depend GPU Usage' done"

}
SetToByAuto(){
    echo "Auto" > $ModulesMode
    echo "update mode to 'auto' done"
}
SetToByDisplay(){
    echo "Display Status" > $ModulesMode
    echo "update mode to 'Display Status' done"
}
GetInfo(){
    echo "Modules Mode By : $(cat $ModulesMode)"
}

if [[ ! -z "${1}" ]];then
    if [[ "${1}" == "off" ]];then
        forceOFF
    elif [[ "${1}" == "on" ]];then
        forceON
    elif [[ "${1}" == "app" ]];then
        SetToByApp
    elif [[ "${1}" == "gpu" ]];then
        SetToByGpu
    elif [[ "${1}" == "auto" ]];then
        SetToByAuto
    elif [[ "${1}" == "display" ]];then
        SetToByDisplay
    elif [[ "${1}" == "info" ]];then
        GetInfo
    else
        Gethelp
    fi
else
    GetInfo
fi